# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regestiration',
            old_name='attend_Tedx',
            new_name='attend_tedx',
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='about_tedx',
            field=models.TextField(verbose_name='\u062a\u062d\u062f\u062b \u0639\u0646 \u062a\u062f\u0643\u0633'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='age',
            field=models.IntegerField(default=0, verbose_name='\u0639\u0645\u0631\u0643'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='city',
            field=models.CharField(default='\u0627\u0644\u0631\u064a\u0627\u0636', max_length=10, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='emial',
            field=models.EmailField(max_length=100, verbose_name='\u0627\u0644\u0628\u0631\u064a\u062f \u0627\u0644\u0625\u0644\u0643\u062a\u0631\u0648\u0646\u064a'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='expectations',
            field=models.TextField(verbose_name='\u0645\u0627 \u0627\u0644\u0630\u064a \u062a\u062a\u0648\u0642\u0639\u0647 \u0645\u0646 TEDxKSAUHS?'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='\u0627\u0644\u0645\u0633\u0645\u0649 \u0627\u0644\u0648\u0638\u064a\u0641\u064a'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='meaning',
            field=models.TextField(verbose_name='\u0645\u0627 \u0627\u0644\u0630\u064a \u062a\u0639\u0646\u064a\u0647 \u0644\u0643 \u0644\u0648 \u0623\u0646\u061f'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='\u0631\u0642\u0645 \u0627\u0644\u062c\u0648\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u0627\u0633\u0645\u0643'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='past_experience',
            field=models.TextField(verbose_name='\u062a\u062d\u062f\u062b \u0639\u0646 \u062a\u062c\u0631\u0628\u062a\u0643 \u0627\u0644\u0633\u0627\u0628\u0642\u0629 \u0645\u0639 \u062a\u062f\u0643\u0633'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='referral',
            field=models.CharField(max_length=20, verbose_name='\u0643\u064a\u0641 \u0633\u0645\u0639\u062a \u0639\u0646 TEDxKSAUHS?'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='your_interest',
            field=models.CharField(choices=[(b'A', '\u0627\u0644\u0641\u0646'), (b'E', '\u0627\u0644\u062a\u0639\u0644\u064a\u0645'), (b'H', '\u0627\u0644\u0635\u062d\u0629'), (b'T', '\u0627\u0644\u062a\u0643\u0646\u0648\u0644\u0648\u062c\u064a\u0627'), (b'S', '\u0627\u0644\u0631\u064a\u0627\u0636\u0629'), (b'B', '\u0631\u064a\u0627\u062f\u0629 \u0627\u0644\u0623\u0639\u0645\u0627\u0644'), (b'V', '\u0627\u0644\u062a\u0637\u0648\u0639'), (b'M', '\u0627\u0644\u062a\u0633\u0648\u064a\u0642'), (b'L', '\u0627\u0644\u0623\u062f\u0628')], max_length=50, verbose_name='\u0627\u064a \u0627\u0644\u0645\u062c\u0627\u0644\u0627\u062a \u0627\u0644\u062a\u0627\u0644\u064a\u0629 \u0623\u0642\u0631\u0628 \u0644\u0627\u0647\u062a\u0645\u0627\u0645\u0643\u061f'),
        ),
        migrations.AlterField(
            model_name='regestiration',
            name='yourself',
            field=models.TextField(verbose_name='\u062a\u062d\u062f\u062b \u0639\u0646 \u0646\u0641\u0633\u0643'),
        ),
    ]
